# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca8582cba23a92b9d91333293b56762fe2c7cc1a155bad2fc79b686870ae87b66047d018cac7ecd8699a7deb25b9f85329f7a75c85a352ea77a2142dce1ad63e

test:
  secret_key_base: a82afbe0575ce32a4e4a9d42d5f806ec50cb72ccf95b6be9a7b30b6a0a4001f30caedd63744c76e4cdad7ebb4333763e8e368415118e1d71a8e1582ab9b8949f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
